version: '3.4'

services:
  app:
    build: ./php7.1
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    networks:
      - backend

  db:
    image: mysql:5.7.20
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db1-esitef
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./database:/var/lib/mysql

networks:
  backend:
